#!/usr/bin/env php
<?php

use function Differ\genDiff;

$autoloadPathGlobal = __DIR__ . '/../../autoload.php';
$autoloadPathLocal = __DIR__ . '/vendor/autoload.php';
if (file_exists($autoloadPathGlobal)) {
    require_once $autoloadPathGlobal;
} else {
    require_once $autoloadPathLocal;
}

$doc = <<<DOC
Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: pretty]

DOC;

$args = Docopt::handle($doc, ['version' => 'Generate diff 1.0']);

$pathToFile1 = $args['<firstFile>'] ?? null;
$pathToFile2 = $args['<secondFile>'] ?? null;

if ($pathToFile1 && $pathToFile2) {
    try {
        $diff = genDiff($pathToFile1, $pathToFile2);
        echo $diff . "\n";
    } catch (Exception $e) {
        echo "gendiff: " . $e->getMessage() . "\n";
    }
}