#!/usr/bin/env php
<?php

$autoloadPathGlobal = __DIR__ . '/../../autoload.php';
$autoloadPathLocal = __DIR__ . '/vendor/autoload.php';
if (file_exists($autoloadPathGlobal)) {
    require_once $autoloadPathGlobal;
} else {
    require_once $autoloadPathLocal;
}

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)

Options:
  -h --help                     Show this screen
  -v --version                  Show version

DOC;

$args = Docopt::handle($doc, ['version' => 'Generate diff 1.0']);
foreach ($args as $k=>$v)
    echo $k . ': ' . json_encode($v) . PHP_EOL;